apiVersion: v1
kind: Secret
metadata:
  name: pathfinder-secrets
type: Opaque
data:
  # These values should be base64 encoded
  # Example: echo -n "your-secret" | base64
  jwt-secret: ${BASE64_JWT_SECRET}
  db-user: ${BASE64_DB_USER}
  db-password: ${BASE64_DB_PASSWORD}